### PR TITLE
Fixes issue 17 - sleep() throws error

### PR DESCRIPTION
**Pull request by dargus**
b"" does not pass properly to the i2cdisplay function as it tries to concatenate a list with a byte string.

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
This well send an extra null byte. Did you try `[]` instead?

**Comment by dargus** [comment]
I had not tried that.  Confirmed that it works in my code.

**Review by EAGrahamJr — COMMENTED** [review]
Well, **I** like it :grinning:

**Review by FoamyGuy — APPROVED** [review]
This looks good to me. The requested change was made in the latest commit. 

Thank you @dargus!

**Pull request merged**
